
import React, { useState, useEffect } from 'react';
import { ClipboardList, UserPlus, History, Send, ShieldCheck, Trash2, Share2 } from 'lucide-react';
import { Visitor } from '../types';

const VisitorRegistry: React.FC = () => {
  const [visitors, setVisitors] = useState<Visitor[]>([]);
  const [name, setName] = useState('');
  const [dept, setDept] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('mdro_visitors');
    if (saved) setVisitors(JSON.parse(saved));
  }, []);

  const handleCheckIn = (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim() || !dept.trim()) return;

    setIsSubmitting(true);
    const newVisitor: Visitor = {
      id: Date.now().toString(),
      name: name.trim(),
      department: dept.trim(),
      timestamp: new Date().toLocaleString('en-GB', { 
        day: '2-digit', month: 'short', year: 'numeric', 
        hour: '2-digit', minute: '2-digit' 
      }),
    };

    const updated = [newVisitor, ...visitors];
    setVisitors(updated);
    localStorage.setItem('mdro_visitors', JSON.stringify(updated));
    
    // Reset form
    setName('');
    setDept('');
    setTimeout(() => setIsSubmitting(false), 500);
  };

  const exportReport = () => {
    if (visitors.length === 0) return alert('No records to export.');
    
    const reportText = visitors.map(v => `${v.timestamp}: ${v.name} (${v.department})`).join('\n');
    const fullMessage = `MDRO LTC 5 - Attendance Report\n--------------------------\n${reportText}\n\nGenerated by Elbermawy LTC`;
    
    // Force direct call for Safari
    if (navigator.share) {
      navigator.share({
        title: 'Attendance Report - MDRO LTC 5',
        text: fullMessage,
      }).catch((err) => {
        if (err.name !== 'AbortError') {
          openWhatsApp(fullMessage);
        }
      });
    } else {
      openWhatsApp(fullMessage);
    }
  };

  const openWhatsApp = (message: string) => {
    const encoded = encodeURIComponent(message);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
  };

  const clearRecords = () => {
    if (window.confirm('Are you sure you want to clear all visitor records?')) {
      setVisitors([]);
      localStorage.removeItem('mdro_visitors');
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <header>
        <h2 className="text-2xl font-bold flex items-center gap-2">
          <ClipboardList className="text-blue-600 w-8 h-8" />
          Visitor Registry
        </h2>
        <p className="text-slate-500">Log your attendance to receive certification updates.</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Check-in Form */}
        <div className="lg:col-span-1">
          <form onSubmit={handleCheckIn} className="bg-white p-6 rounded-[2.5rem] border border-slate-100 shadow-sm space-y-4">
            <div className="flex items-center gap-2 mb-2">
              <div className="bg-blue-100 p-2 rounded-xl text-blue-600">
                <UserPlus className="w-5 h-5" />
              </div>
              <h3 className="font-bold text-lg">Check-in</h3>
            </div>
            
            <div className="space-y-3">
              <div>
                <label className="text-xs font-bold text-slate-400 uppercase ml-1">Full Name</label>
                <input 
                  required
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Enter your name..."
                  className="w-full bg-slate-50 border-none rounded-2xl px-5 py-4 text-sm focus:ring-2 focus:ring-blue-500 outline-none mt-1"
                />
              </div>
              <div>
                <label className="text-xs font-bold text-slate-400 uppercase ml-1">Department / Title</label>
                <input 
                  required
                  value={dept}
                  onChange={(e) => setDept(e.target.value)}
                  placeholder="e.g. ICU Nurse, Physician..."
                  className="w-full bg-slate-50 border-none rounded-2xl px-5 py-4 text-sm focus:ring-2 focus:ring-blue-500 outline-none mt-1"
                />
              </div>
              <button 
                type="submit"
                disabled={isSubmitting}
                className="w-full bg-blue-600 text-white py-4 rounded-2xl font-bold hover:bg-blue-700 transition-all shadow-lg shadow-blue-100 flex items-center justify-center gap-2 active:scale-95 disabled:opacity-50"
              >
                {isSubmitting ? 'Registering...' : 'Log Attendance'}
                <ShieldCheck className="w-5 h-5" />
              </button>
            </div>
          </form>
        </div>

        {/* History List */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex items-center justify-between px-2">
            <div className="flex items-center gap-2">
              <History className="text-slate-400 w-5 h-5" />
              <h3 className="font-bold">Recent Visitors ({visitors.length})</h3>
            </div>
            <div className="flex gap-2">
              <button 
                onClick={exportReport}
                className="p-2 text-emerald-600 bg-emerald-50 rounded-xl hover:bg-emerald-100 transition-colors flex items-center gap-2 text-sm font-bold border border-emerald-100"
                title="Share Report"
              >
                <Share2 className="w-4 h-4" /> Export Report
              </button>
              <button 
                onClick={clearRecords}
                className="p-2 text-red-600 bg-red-50 rounded-xl hover:bg-red-100 transition-colors"
                title="Clear All"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          </div>

          <div className="bg-white rounded-[2.5rem] border border-slate-100 shadow-sm overflow-hidden">
            {visitors.length > 0 ? (
              <div className="divide-y divide-slate-50">
                {visitors.map((v) => (
                  <div key={v.id} className="p-5 flex items-center justify-between hover:bg-slate-50 transition-colors">
                    <div className="flex items-center gap-4">
                      <div className="w-12 h-12 bg-blue-50 rounded-2xl flex items-center justify-center text-blue-600 font-bold uppercase">
                        {v.name.charAt(0)}
                      </div>
                      <div>
                        <p className="font-bold text-slate-800">{v.name}</p>
                        <p className="text-xs text-slate-400">{v.department}</p>
                      </div>
                    </div>
                    <div className="text-right">
                      <p className="text-[10px] font-bold text-slate-300 uppercase">{v.timestamp}</p>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="p-12 text-center text-slate-400">
                <ClipboardList className="w-12 h-12 mx-auto mb-3 opacity-10" />
                <p>No attendance logs yet.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default VisitorRegistry;
